[package]
name = "tokenizers-python"
version = "0.3.0"
authors = ["Anthony MOI <m.anthony.moi@gmail.com>"]
edition = "2018"

[lib]
name = "tokenizers"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.8.4"
features = ["extension-module"]

[dependencies.tokenizers]
version = "*"
path = "../../tokenizers"

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
